### ISSUE TITLE
java.io.IOException: Failed to load http://<server url>/computer/<node name>/slave-agent.jnlp: 404 Not Found

### ISSUE THREAD

**Issue by lmilbaum** [kobanyan/jenkins-jnlp-slave#2]
Failing to obtain http://10.0.0.102/computer/ip-10-0-0-187/slave-agent.jnlp
java.io.IOException: Failed to load http://10.0.0.102/computer/ip-10-0-0-187/slave-agent.jnlp: 404 Not Found
	at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:399)
	at hudson.remoting.Launcher.run(Launcher.java:248)
	at hudson.remoting.Launcher.main(Launcher.java:218)
Waiting 10 seconds before retry
Failing to obtain http://10.0.0.102/computer/ip-10-0-0-187/slave-agent.jnlp
java.io.IOException: Failed to load http://10.0.0.102/computer/ip-10-0-0-187/slave-agent.jnlp: 404 Not Found
	at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:399)
	at hudson.remoting.Launcher.run(Launcher.java:248)
	at hudson.remoting.Launcher.main(Launcher.java:218)
Waiting 10 seconds before retry
Failing to obtain http://10.0.0.102/computer/ip-10-0-0-187/slave-agent.jnlp
java.io.IOException: Failed to load http://10.0.0.102/computer/ip-10-0-0-187/slave-agent.jnlp: 404 Not Found
	at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:399)
	at hudson.remoting.Launcher.run(Launcher.java:248)
	at hudson.remoting.Launcher.main(Launcher.java:218)
Waiting 10 seconds before retry

**Comment by lmilbaum** [comment]
Maybe, the root cause is missing secret. Can we generate the secret the same way as done in the chef cookbook: 
https://github.com/chef-cookbooks/jenkins/blob/2e8de0ef356cc9cc0fcf440c6d96c131110a4aae/libraries/slave_jnlp.rb

**Comment by kobanyan** [comment]
I can not reproduce it.
Have you created 'ip-10-0-0-187' node on Jenkins master?
This role does not create node on Jenkins master.

**Comment by vijaykumarcm** [comment]
Failed to obtain http://localhost:8080/Testing/computer/Local_Node/slave-agent.jnlp?encrypt=true
java.io.IOException: Failed to load http://localhost:8080/Testing/computer/Local_Node/slave-agent.jnlp?encrypt=true: 403 Forbidden
	at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:519)
	at hudson.remoting.Launcher.run(Launcher.java:347)
	at hudson.remoting.Launcher.main(Launcher.java:298)
